title: Anuj Badave
logo: /assets/me.jpg
description: Passionate Data Science Aspirant. Eager to apply analytical skills to real-world challenges, committed to continuous learning in the field of data science.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
